version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n
      GENERIC_TIMEZONE: America/Sao_Paulo
      N8N_CUSTOM_EXTENSIONS: /home/node/custom-nodes
    volumes:
      # Volume para persistir dados do n8n
      - n8n_data:/home/node/.n8n
      # Monta sua pasta local de conectores no container
      - ./src/custom-nodes:/home/node/custom-nodes
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  n8n_data:
